# -*- coding: utf-8 -*-

# Configuration used to run an algorithm on CartPole environment
# --------------------------------------------------------------
# Set a random seed
seed: 0

# Set
num_iterations: 10000

# Set
eval_interval: 5

# Set
threshold_return: 500

# Set
is_only_eval: False

# Set
use_rendering: False