# -*- coding: utf-8 -*-

# Main configuration
# ------------------
# Choose an environment among cartpole, pendulum, mujoco, and bullet
env_name: "cartpole"

# Choose an algorithm among dqn, ddqn, a2c, vpg, npg, trpo, ppo, ddpg, td3, sac, and sac-aea
#   - cartpole: dqn, ddqn, and a2c
#   - pendulum: vpg, npg, trpo, ppo, ddpg, td3, sac, and sac-aea
#   - mujoco: vpg, npg, trpo, ppo, ddpg, td3, sac, and sac-aea
#   - bullet: vpg, npg, trpo, ppo, ddpg, td3, sac, and sac-aea
algo_name: "dqn"

# Set experiment name
exp_name: "exp_1"

# Set file name
file_name: null

# Set GPU index
gpu_index: 0
